# MOVIE RECCOMENDATION MODEL

## 1. BUSINESS UNDERSTANDING
#### 1.1 Problem Statement

Streaming platforms such as Netflix and Showmax offer thousands of movies, making it difficult for users to quickly find content they will enjoy. When users cannot easily find relevant movies, they may become frustrated, spend less time on the platform, or stop using it. Additionally, new users and newly added movies often lack sufficient rating data, creating what is known as the cold start problem. This reduces the effectiveness of traditional recommendation systems.

This project aims to solve this problem by developing a hybrid movie recommendation system that suggests the top 5 personalized movies to users based on both their past ratings and movie content.

#### 1.2 Business Objective

The main goal of this project is to improve user experience and - on a streaming platform by providing accurate and personalized movie recommendations.

Specifically, the system should:

1. Help users discover movies they are likely to enjoy
2. Reduce the time users spend searching for content
3. Increase user satisfaction and retention
4. Improve overall platform usage and watch time
#### 1.3 Project Objectives

To achieve the business goal, this project will:

1. Build a collaborative filtering model using user ratings
2. Develop a content-based filtering model using movie descriptions and genres (NLP techniques)
3. Combine both approaches into a hybrid recommendation system
4. Recommend the top 5 movies for each user
5. Handle the cold start problem using content-based methods
6. Evaluate model performance using appropriate metrics such as RMSE and similarity scores
7. Compare different models, including a neural network model, to find the best-performing approach
#### 1.4 Stakeholders

The key stakeholders in this project include:

1. Streaming Platform (Business/Product Team)- They will use the recommendation system to improve the platform and the goal is to increase user engagement, retention, and revenue
2. Platform Users (Viewers)- They receive personalized movie recommendations and the goal is to quickly find movies they enjoy

#### 1.5 Key Questions

To guide the project, the following questions need to be answered:

1. How can we accurately recommend movies to users based on their preferences?
2. How do we handle users with little or no rating history?
3. How can movie descriptions and genres improve recommendation quality?
4. Which model performs best: collaborative filtering, content-based, or hybrid?
5. How do we ensure the recommendations are relevant and personalized?

#### 1.6 Data Sources

This project will use two main datasets:

1. MovieLens Dataset

Contains user ratings for movies (Includes variables such as userId, movieId, and rating). This dataset will be used to build the collaborative filtering model

2. TMDB (The Movie Database) Dataset

Contains movie metadata such as titles, genres, and descriptions (overview). This dataset will be used for content-based filtering using Natural Language Processing (NLP) techniques

These two datasets will be combined to build a hybrid recommendation system that leverages both user behavior and movie content.

## 2. DATA UNDERSTANDING

This project uses three datasets to build a hybrid reccomendation system. The Movielens dataset which has both the movies and the ratings data, and the TMDB dataset which contain movie metadata.

#### Import the neccessary libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#### Loading the datasets

In [2]:
# Loading the movies data
movies_df=pd.read_csv("Data sets/movies.csv")
ratings_df = pd.read_csv('Data sets/ratings.csv')
tmdb_df= pd.read_csv('Data sets/TMDB_movie_dataset_v11.csv')

movies_df.head()
ratings_df.head()
tmdb_df.head()

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,Interstellar,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,The Avengers,When an unexpected enemy emerges and threatens...,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com..."

In [3]:
# Checking the size of the dataset
movies_df.shape, ratings_df.shape, tmdb_df.shape

((9742, 3), (100836, 4), (1407344, 24))

#### Check the structure of the dataset (columns, data types, and missing values)

In [4]:
# Check the structure of the dataset (columns, data types, and missing values)
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   title    9742 non-null   object
 2   genres   9742 non-null   object
dtypes: int64(1), object(2)
memory usage: 228.5+ KB

In [5]:
ratings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userId     100836 non-null  int64
 1   movieId    100836 non-null  int64
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 3.1 MB

In [6]:
tmdb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1407344 entries, 0 to 1407343
Data columns (total 24 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   id                    1407344 non-null  int64
 1   title                 1407326 non-null  object
 2   vote_average          1407344 non-null  float64
 3   vote_count            1407344 non-null  int64
 4   status                1407344 non-null  object
 5   release_date          1097755 non-null  object
 6   revenue               1407344 non-null  int64
 7   runtime               1407344 non-null  int64
 8   adult                 1407344 non-null  bool
 9   backdrop_path         350459 non-null   object
 10  budget                1407344 non-null  int64
 11  homepage              144944 non-null   object
 12  imdb_id               665648 non-null   object
 13  original_language     1407344 non-null  object
 14  original_title        1407326 non-null  object
 15  overview              1085602 non-null  object
 16  popularity            1407344 non-null  float64
 17  poster_path           909200 non-null   object
 18  tagline               195889 non-null   object
 19  genres                790769 non-null   object
 20  production_companies  600459 non-null   object
 21  production_countries  728369 non-null   object
 22  spoken_languages      755376 non-null   object
 23  keywords              349079 non-null   object
dtypes: bool(1), float64(2), int64(5), object(16)
memory usage: 248.3+ MB

In [7]:
# check columns for all datasets

print("columns for the tmdb dataset " , tmdb_df.columns)
print("columns for the movies dataset " , movies_df.columns)
print("columns for the ratings dataset " , ratings_df.columns)

columns for the tmdb dataset  Index(['id', 'title', 'vote_average', 'vote_count', 'status', 'release_date',
       'revenue', 'runtime', 'adult', 'backdrop_path', 'budget', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'tagline', 'genres',
       'production_companies', 'production_countries', 'spoken_languages',
       'keywords'],
      dtype='object')
columns for the movies dataset  Index(['movieId', 'title', 'genres'], dtype='object')
columns for the ratings dataset  Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='object')

In [8]:
ratings_df.value_counts("userId")

userId
414    2698
599    2478
474    2108
448    1864
274    1346
       ...
442      20
569      20
320      20
576      20
53       20
Name: count, Length: 610, dtype: int64

In [9]:
# check the movie ids in the all datasets to see if they match and can be used for merging

print("unique movie ids in tmdb dataset " , tmdb_df["id"].nunique())
print("unique movie ids in movies dataset " , movies_df["movieId"].nunique())
print("unique movie ids in ratings dataset " , ratings_df["movieId"].nunique())

unique movie ids in tmdb dataset  1406112
unique movie ids in movies dataset  9742
unique movie ids in ratings dataset  9724

#### Checking for missing values

In [10]:
# Check missing values in each dataset

print("Missing values in TMDB dataset:\n", tmdb_df.isnull().sum(), "\n")

print("Missing values in Movies dataset:\n", movies_df.isnull().sum(), "\n")

print("Missing values in Ratings dataset:\n", ratings_df.isnull().sum())

Missing values in TMDB dataset:
 id                            0
title                        18
vote_average                  0
vote_count                    0
status                        0
release_date             309589
revenue                       0
runtime                       0
adult                         0
backdrop_path           1056885
budget                        0
homepage                1262400
imdb_id                  741696
original_language             0
original_title               18
overview                 321742
popularity                    0
poster_path              498144
tagline                 1211455
genres                   616575
production_companies     806885
production_countries     678975
spoken_languages         651968
keywords                1058265
dtype: int64

Missing values in Movies dataset:
 movieId    0
title      0
genres     0
dtype: int64

Missing values in Ratings dataset:
 userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

The TMDB datasets is the only one with missing values in some columns.

## 3. DATA CLEANING

#### Standardizing Column Names

In [11]:
# Define a function to standardize column names by removing extra spaces,
# converting to lowercase, and replacing spaces with underscores for consistency
def normalize_columns(df):
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
    )
    return df

# Apply the normalization function to all datasets to ensure uniform column naming
movies_df = normalize_columns(movies_df)
ratings_df = normalize_columns(ratings_df)
tmdb_df = normalize_columns(tmdb_df)

# Print column names from each dataset to verify that normalization was successful
print("columns for the tmdb dataset ", tmdb_df.columns)
print("columns for the movies dataset ", movies_df.columns)
print("columns for the ratings dataset ", ratings_df.columns)

columns for the tmdb dataset  Index(['id', 'title', 'vote_average', 'vote_count', 'status', 'release_date',
       'revenue', 'runtime', 'adult', 'backdrop_path', 'budget', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'tagline', 'genres',
       'production_companies', 'production_countries', 'spoken_languages',
       'keywords'],
      dtype='object')
columns for the movies dataset  Index(['movieid', 'title', 'genres'], dtype='object')
columns for the ratings dataset  Index(['userid', 'movieid', 'rating', 'timestamp'], dtype='object')

####  Converting Data Types for Efficiency and Consistency

In [12]:
# Convert data types to more memory-efficient formats
ratings_df = ratings_df.astype({
    "userid": "int32",
    "movieid": "int32",
    "rating": "float32"
})

# Ensure consistency of key columns across datasets by converting IDs to int32
movies_df["movieid"] = movies_df["movieid"].astype("int32")
tmdb_df["id"] = tmdb_df["id"].astype("int32")

# Verify that data type conversions were successful by checking the dtypes
print("data types for the tmdb dataset ", tmdb_df[["id"]].dtypes)
print("data types for the movies dataset ", movies_df[["movieid"]].dtypes)
print("data types for the ratings dataset ", ratings_df[["userid", "movieid", "rating"]].dtypes)

data types for the tmdb dataset  id    int32
dtype: object
data types for the movies dataset  movieid    int32
dtype: object
data types for the ratings dataset  userid       int32
movieid      int32
rating     float32
dtype: object

#### Timestamp Handling for ratings dataset

In [13]:
ratings_df["timestamp"] = pd.to_datetime(ratings_df["timestamp"], unit="s")

# check the data types again to confirm the timestamp is converted correctly
print("data types for the ratings dataset " , ratings_df[["timestamp"]].dtypes)

data types for the ratings dataset  timestamp    datetime64[ns]
dtype: object

#### Dropping Irrelevant Features from TMDB Dataset

In [14]:
# Drop unnecessary or irrelevant columns from the TMDB dataset
# These features are removed because they are not useful for the recommendation task
# and may add noise or unnecessary complexity to the dataset.
# Removed columns include: backdrop_path, poster_path, homepage, status,
# production_companies, production_countries, and spoken_languages

tmdb_df_dropped = tmdb_df.drop(columns=[
    "backdrop_path",
    "poster_path",
    "homepage",
    "status",
    "production_companies",
    "production_countries",
    "spoken_languages",
    "imdb_id"
])

In [15]:
#check the structure of the TMDB dataset after dropping the columns
tmdb_df_dropped.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1407344 entries, 0 to 1407343
Data columns (total 16 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   id                 1407344 non-null  int32
 1   title              1407326 non-null  object
 2   vote_average       1407344 non-null  float64
 3   vote_count         1407344 non-null  int64
 4   release_date       1097755 non-null  object
 5   revenue            1407344 non-null  int64
 6   runtime            1407344 non-null  int64
 7   adult              1407344 non-null  bool
 8   budget             1407344 non-null  int64
 9   original_language  1407344 non-null  object
 10  original_title     1407326 non-null  object
 11  overview           1085602 non-null  object
 12  popularity         1407344 non-null  float64
 13  tagline            195889 non-null   object
 14  genres             790769 non-null   object
 15  keywords           349079 non-null   object
dtypes: bool(1), float64(2), int32(1), int64(4), object(8)
memory usage: 157.0+ MB

In [16]:
#check the shape of the TMDB dataset after dropping the columns
tmdb_df_dropped.shape

(1407344, 16)

In [17]:
import re  # Import regular expressions for advanced text cleaning

# Function to clean movie titles for better matching and consistency
def clean_title(title):
    # Handle missing values by returning an empty string
    if pd.isna(title):
        return ""
    
    title = title.lower()
    title = re.sub(r"\(\d{4}\)", "", title)   # remove year
    title = re.sub(r"[^a-z0-9 ]", "", title)  # remove punctuation
    title = re.sub(r"\s+", " ", title)        # normalize spaces
    return title.strip()

# Apply cleaning function to movie titles in both datasets
movies_df["clean_title"] = movies_df["title"].apply(clean_title)
tmdb_df_dropped["clean_title"] = tmdb_df_dropped["title"].apply(clean_title)

In [18]:
# check the titles after cleaning to confirm they are cleaned correctly
print("cleaned titles in the tmdb dataset\n" , tmdb_df_dropped["clean_title"].head())
print("\ncleaned titles in the movies dataset\n" , movies_df["clean_title"].head())

cleaned titles in the tmdb dataset
 0          inception
1       interstellar
2    the dark knight
3             avatar
4       the avengers
Name: clean_title, dtype: object

cleaned titles in the movies dataset
 0                      toy story
1                        jumanji
2               grumpier old men
3              waiting to exhale
4    father of the bride part ii
Name: clean_title, dtype: object

In [19]:
print("colums after " , movies_df.columns)
print("colums after " , tmdb_df_dropped.columns)

colums after  Index(['movieid', 'title', 'genres', 'clean_title'], dtype='object')
colums after  Index(['id', 'title', 'vote_average', 'vote_count', 'release_date', 'revenue',
       'runtime', 'adult', 'budget', 'original_language', 'original_title',
       'overview', 'popularity', 'tagline', 'genres', 'keywords',
       'clean_title'],
      dtype='object')

### 3.2 Handle Duplicates

In [20]:
# Check and display the number of duplicate rows in each dataset

print("Duplicate rows in TMDB dataset:", tmdb_df_dropped.duplicated().sum())

print("Duplicate rows in Movies dataset:", movies_df.duplicated().sum())

print("Duplicate rows in Ratings dataset:", ratings_df.duplicated().sum())

Duplicate rows in TMDB dataset: 388
Duplicate rows in Movies dataset: 0
Duplicate rows in Ratings dataset: 0

In [21]:
# drop duplicates in the tmdb dataset
tmdb_df_dropped = tmdb_df_dropped.drop_duplicates()

#check if dropped duplicates in the tmdb dataset
print("duplicates in the tmdb dataset after dropping " , tmdb_df_dropped.duplicated().sum())

duplicates in the tmdb dataset after dropping  0

#### Handling missing values in the TMDB dataset

In [22]:
print("Missing values in TMDB dataset:\n", tmdb_df_dropped.isnull().sum())

Missing values in TMDB dataset:
 id                         0
title                     18
vote_average               0
vote_count                 0
release_date          309368
revenue                    0
runtime                    0
adult                      0
budget                     0
original_language          0
original_title            18
overview              321620
popularity                 0
tagline              1211112
genres                616296
keywords             1057963
clean_title                0
dtype: int64

In [23]:
tmdb_df_dropped["overview"] = tmdb_df_dropped["overview"].fillna("unknown")
tmdb_df_dropped["keywords"] = tmdb_df_dropped["keywords"].fillna("unknown")
tmdb_df_dropped["genres"] = tmdb_df_dropped["genres"].fillna("unknown")
tmdb_df_dropped = tmdb_df_dropped.dropna(subset=["title", "original_title"])
tmdb_df_dropped["tagline"] = tmdb_df_dropped["tagline"].fillna("unknown")

In [24]:
tmdb_df_dropped["release_year"] = pd.to_datetime(
    tmdb_df_dropped["release_date"], errors="coerce"
).dt.year

# check the structure of the release_year column after extracting the year to confirm it is extracted correctly
print(tmdb_df_dropped["release_year"].head())
print(tmdb_df_dropped["release_year"].isnull().sum())

0    2010.0
1    2014.0
2    2008.0
3    2009.0
4    2012.0
Name: release_year, dtype: float64
309354

In [25]:
# handle null values and also convert to string type for the content column which will be used for the NLP analysis
tmdb_df_dropped["release_year"] = tmdb_df_dropped["release_year"].fillna(0).astype(int).astype(str)

In [26]:
tmdb_df_dropped = tmdb_df_dropped.drop(columns=["release_date"])

In [27]:
print("Missing values in TMDB dataset:\n", tmdb_df_dropped.isnull().sum())

Missing values in TMDB dataset:
 id                   0
title                0
vote_average         0
vote_count           0
revenue              0
runtime              0
adult                0
budget               0
original_language    0
original_title       0
overview             0
popularity           0
tagline              0
genres               0
keywords             0
clean_title          0
release_year         0
dtype: int64

In [28]:
print(tmdb_df_dropped.dtypes)
print(movies_df.dtypes)
print(ratings_df.dtypes)

id                     int32
title                 object
vote_average         float64
vote_count             int64
revenue                int64
runtime                int64
adult                   bool
budget                 int64
original_language     object
original_title        object
overview              object
popularity           float64
tagline               object
genres                object
keywords              object
clean_title           object
release_year          object
dtype: object
movieid         int32
title          object
genres         object
clean_title    object
dtype: object
userid                int32
movieid               int32
rating              float32
timestamp    datetime64[ns]
dtype: object

### MERGE THE DATASETS

In [29]:
movie_metadata = movies_df.merge(
    tmdb_df_dropped,
    on="clean_title",
    how="inner"
)
# This ensures that those movies that are present in both datasets are retained, while those that do not have a match in either dataset are excluded.

In [30]:
#check the structure of the merged dataset
movie_metadata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33323 entries, 0 to 33322
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   movieid            33323 non-null  int32
 1   title_x            33323 non-null  object
 2   genres_x           33323 non-null  object
 3   clean_title        33323 non-null  object
 4   id                 33323 non-null  int32
 5   title_y            33323 non-null  object
 6   vote_average       33323 non-null  float64
 7   vote_count         33323 non-null  int64
 8   revenue            33323 non-null  int64
 9   runtime            33323 non-null  int64
 10  adult              33323 non-null  bool
 11  budget             33323 non-null  int64
 12  original_language  33323 non-null  object
 13  original_title     33323 non-null  object
 14  overview           33323 non-null  object
 15  popularity         33323 non-null  float64
 16  tagline            33323 non-null  object
 17  genres_y           33323 non-null  object
 18  keywords           33323 non-null  object
 19  release_year       33323 non-null  object
dtypes: bool(1), float64(2), int32(2), int64(4), object(11)
memory usage: 4.6+ MB

In [31]:
movie_metadata.head()

,movieid,title_x,genres_x,clean_title,id,title_y,vote_average,vote_count,revenue,runtime,adult,budget,original_language,original_title,overview,popularity,tagline,genres_y,keywords,release_year
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,toy story,862,Toy Story,7.971,17152,394400000,81,False,30000000,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",78.404,Hang on for the comedy that goes to infinity a...,"Animation, Adventure, Family, Comedy","rescue, friendship, mission, martial arts, jea...",1995
1,2,Jumanji (1995),Adventure|Children|Fantasy,jumanji,8844,Jumanji,7.239,9833,262821940,104,False,65000000,en,Jumanji,When siblings Judy and Peter discover an encha...,13.444,Roll the dice and unleash the excitement!,"Adventure, Fantasy, Family","giant insect, board game, disappearance, jungl...",1995
2,3,Grumpier Old Men (1995),Comedy|Romance,grumpier old men,15602,Grumpier Old Men,6.476,347,71500000,101,False,25000000,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,14.815,Still Yelling. Still Fighting. Still Ready for...,"Romance, Comedy","fishing, sequel, old man, best friend, wedding...",1995
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,waiting to exhale,31357,Waiting to Exhale,6.183,142,81452156,127,False,16000000,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",14.451,Friends are the people who let you be yourself...,"Comedy, Drama, Romance","based on novel or book, interracial relationsh...",1995
4,5,Father of the Bride Part II (1995),Comedy,father of the bride part ii,11862,Father of the Bride Part II,6.228,659,76594107,106,False,0,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,14.537,Just when his world is back to normal... he's ...,"Comedy, Family","daughter, baby, parent child relationship, mid...",1995

In [32]:
movie_metadata.shape

(33323, 20)

In [33]:
# merge the ratings dataset with the movie metadata dataset to get the final dataset for analysis
final_dataset = ratings_df.merge(
    movie_metadata,
    on="movieid",
    how="inner"
)
print("structure of the final dataset " , final_dataset.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320816 entries, 0 to 320815
Data columns (total 23 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   userid             320816 non-null  int32
 1   movieid            320816 non-null  int32
 2   rating             320816 non-null  float32
 3   timestamp          320816 non-null  datetime64[ns]
 4   title_x            320816 non-null  object
 5   genres_x           320816 non-null  object
 6   clean_title        320816 non-null  object
 7   id                 320816 non-null  int32
 8   title_y            320816 non-null  object
 9   vote_average       320816 non-null  float64
 10  vote_count         320816 non-null  int64
 11  revenue            320816 non-null  int64
 12  runtime            320816 non-null  int64
 13  adult              320816 non-null  bool
 14  budget             320816 non-null  int64
 15  original_language  320816 non-null  object
 16  original_title     320816 non-null  object
 17  overview           320816 non-null  object
 18  popularity         320816 non-null  float64
 19  tagline            320816 non-null  object
 20  genres_y           320816 non-null  object
 21  keywords           320816 non-null  object
 22  release_year       320816 non-null  object
dtypes: bool(1), datetime64[ns](1), float32(1), float64(2), int32(3), int64(4), object(11)
memory usage: 49.3+ MB
structure of the final dataset  None

In [34]:
final_dataset.head()

,userid,movieid,rating,timestamp,title_x,genres_x,clean_title,id,title_y,vote_average,...,adult,budget,original_language,original_title,overview,popularity,tagline,genres_y,keywords,release_year
0,1,1,4.0,2000-07-30 18:45:03,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,toy story,862,Toy Story,7.971,...,False,30000000,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",78.404,Hang on for the comedy that goes to infinity a...,"Animation, Adventure, Family, Comedy","rescue, friendship, mission, martial arts, jea...",1995
1,1,3,4.0,2000-07-30 18:20:47,Grumpier Old Men (1995),Comedy|Romance,grumpier old men,15602,Grumpier Old Men,6.476,...,False,25000000,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,14.815,Still Yelling. Still Fighting. Still Ready for...,"Romance, Comedy","fishing, sequel, old man, best friend, wedding...",1995
2,1,6,4.0,2000-07-30 18:37:04,Heat (1995),Action|Crime|Thriller,heat,949,Heat,7.903,...,False,60000000,en,Heat,Obsessive master thief Neil McCauley leads a t...,41.522,A Los Angeles crime saga.,"Action, Crime, Drama","robbery, chase, obsession, detective, heist, t...",1995
3,1,6,4.0,2000-07-30 18:37:04,Heat (1995),Action|Crime|Thriller,heat,42023,Heat,5.900,...,False,0,en,Heat,Reynolds plays an ex-soldier-of-fortunish char...,3.913,unknown,"Action, Thriller",unknown,1986
4,1,6,4.0,2000-07-30 18:37:04,Heat (1995),Action|Crime|Thriller,heat,4579,Heat,5.979,...,False,0,en,Heat,"Former child star Joe Davis, reduced to living...",2.521,unknown,"Comedy, Drama","ladykiller, diva, seduction, satire, older wom...",1972

In [35]:
final_dataset.isnull().sum()

userid               0
movieid              0
rating               0
timestamp            0
title_x              0
genres_x             0
clean_title          0
id                   0
title_y              0
vote_average         0
vote_count           0
revenue              0
runtime              0
adult                0
budget               0
original_language    0
original_title       0
overview             0
popularity           0
tagline              0
genres_y             0
keywords             0
release_year         0
dtype: int64

In [36]:
final_dataset.duplicated().sum()

0

In [37]:
final_dataset.columns

Index(['userid', 'movieid', 'rating', 'timestamp', 'title_x', 'genres_x',
       'clean_title', 'id', 'title_y', 'vote_average', 'vote_count', 'revenue',
       'runtime', 'adult', 'budget', 'original_language', 'original_title',
       'overview', 'popularity', 'tagline', 'genres_y', 'keywords',
       'release_year'],
      dtype='object')

In [38]:
# Rename and drop duplicates
final_dataset = final_dataset.rename(columns={
    "title_x": "title",
    "genres_x": "genres"
})

final_dataset = final_dataset.drop(columns=["title_y", "genres_y"])

In [39]:
# Apply mapping according to the iso standard to convert the language codes to language names


language_map = {
    "en": "English",
    "fr": "French",
    "zh": "Chinese",
    "ru": "Russian",
    "es": "Spanish",
    "ja": "Japanese",
    "de": "German",
    "pt": "Portuguese",
    "ko": "Korean",
    "it": "Italian",
    "fa": "Persian",
    "hi": "Hindi",
    "xx": "No Language",
    "ar": "Arabic",
    "tr": "Turkish",
    "pl": "Polish",
    "cn": "Cantonese/Chinese",
    "cs": "Czech",
    "nl": "Dutch",
    "el": "Greek",
    "ta": "Tamil",
    "id": "Indonesian",
    "tl": "Tagalog",
    "sv": "Swedish",
    "os": "Ossetian",
    "dv": "Divehi",
    "wo": "Wolof",
    "nv": "Navajo",
    "mi": "Maori"
}

# Apply the mapping to your dataset
final_dataset['language_name'] = final_dataset['original_language'].map(language_map)

In [40]:
final_dataset['language_name'] = final_dataset['original_language'].fillna('unknown')

In [41]:
final_dataset.isna().sum()

userid               0
movieid              0
rating               0
timestamp            0
title                0
genres               0
clean_title          0
id                   0
vote_average         0
vote_count           0
revenue              0
runtime              0
adult                0
budget               0
original_language    0
original_title       0
overview             0
popularity           0
tagline              0
keywords             0
release_year         0
language_name        0
dtype: int64

In [43]:
# save the clean final datset

final_dataset.to_csv("Data sets/final_dat.csv", index=False)

In [49]:
final_dataset.isna().sum()

userid               0
movieid              0
rating               0
timestamp            0
title                0
genres               0
clean_title          0
id                   0
vote_average         0
vote_count           0
revenue              0
runtime              0
adult                0
budget               0
original_language    0
original_title       0
overview             0
popularity           0
tagline              0
keywords             0
release_year         0
language_name        0
dtype: int64

### Data Cleaning Summary

At this stage, the dataset has been fully cleaned and prepared for modeling. All missing values have been handled appropriately, and the data has been standardized to ensure consistency across features.

Key preprocessing steps included:
- Handling missing values in both numerical and text-based features  
- Standardizing the rating scale to a consistent range  
- Cleaning text features for content-based modeling  
- Removing duplicates and ensuring data integrity  

The dataset is now in a structured and reliable format, ready for feature engineering and model development.